In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
np1_array = np.array((1, 2, 3))

In [6]:
np1_array

array([1, 2, 3])

In [12]:
for col in np1_array:
    print(col)

1
2
3


In [7]:
np2_array = np.array([(1, 2, 3), (4, 5, 6)])

In [8]:
np2_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
for row in np2_array:
    print(row)
    for col in row:
        if(col > 2):
            col = 0
            print(col)
        

[1 2 3]
0
[4 5 6]
0
0
0


In [21]:
for row in np2_array:
    print(row)
    for col in row:
        col = int(col * 0.6)
        print(col)

[1 2 3]
0
1
1
[4 5 6]
2
3
3


In [10]:
np3_array = np.array([[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]])

In [11]:
np3_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
for dim in np3_array:
    print(dim)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [18]:
for dim in np3_array:
    for row in dim:
        print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [19]:
for dim in np3_array:
    for row in dim:
        for col in row:
            print(col)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
for dim in np3_array:
    for row in dim:
        for col in row:
            if(col <= 5):
                col = 0
            print(col)

0
0
0
0
0
6
7
8
9
10
11
12
