In [1]:
import numpy as np
listem = [1,2,3]
type(listem)

list

In [2]:
dizim = np.array(listem)
type(dizim)

numpy.ndarray

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(shape=(5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(shape=(5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
cv2.imshow()