In [1]:
import numpy as np 

# The basics

In [16]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimensions
a.ndim

1

In [5]:
b.ndim

2

In [7]:
# Get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [17]:
# Get type
a.dtype

dtype('int32')

In [18]:
# Get Size
a.itemsize

4

In [19]:
# Get total size
a.size # or a.nbytes

3

## Accessing/Changing specific elements, rows, columns, etc

In [26]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Get element [r, c]
c[1, 5]

13

In [43]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [44]:
# Getting a littlemore fancy
c[0, 1:-1:2]

array([2, 4, 6])

In [45]:
# Change value
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [52]:
c[:,2] = 20
print(c)

[[ 9  8 20  6  5  4  3]
 [ 9  8 20  6  5  4  3]]


In [51]:
# replace
c[:1,:] = [[9,8,7,6,5,4,3]]
print(c)

[[9 8 7 6 5 4 3]
 [9 8 7 6 5 4 3]]


## Initializing Different Types of Arrays

In [53]:
#zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
#np.ones(shape, dtype=None, order='C', *, like=None)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# np.full(shape, fill_value, dtype=None, order='C', *, like=None)
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [57]:
#
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.04581336, 0.14167301],
       [0.65696918, 0.54212303],
       [0.95453279, 0.77206786],
       [0.11168814, 0.71657139]])

In [64]:
# Random integer numbers
np.random.randint(255, size=(3,3))

array([[209,  85,  33],
       [155, 205, 134],
       [ 55,  40, 159]])

In [65]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## mathematics

In [66]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a * 2

array([2, 4, 6, 8])